import asyncio
import json
import os
import re
from datetime import datetime, timezone
from typing import List
from uuid import uuid4

from langchain_community.chat_models import ChatOllama
from langchain_core.documents import Document
from langchain_core.messages import HumanMessage
from pydantic import BaseModel, Field, ValidationError

from core.graph_store import get_graph_store
from core.vector_store import get_vector_store


def get_ingestion_llm():
    if os.getenv("USE_CLOUD_LLM", "false").lower() == "true":
        from langchain_groq import ChatGroq
        # Groq fallback for CPU developers (fast inference)
        return ChatGroq(model="llama3-8b-8192", temperature=0.1)

    # Native Edge Inference
    return ChatOllama(
        base_url=os.getenv("OLLAMA_BASE_URL", "http://127.0.0.1:11434"),
        model="llama3.2:1b",
        temperature=0.1,
    )


llm = get_ingestion_llm()


class ScreenConcept(BaseModel):
    concept_type: str = Field(
        description="The strict classification of the extracted data. MUST be one of: 'API_KEY', 'PASSWORD', 'CREDENTIAL', 'FINANCIAL_DATA', or 'PERSONAL_IDENTIFIER'."
    )
    concept_value: str = Field(
        description="The exact, raw string value of the secret or concept, stripped of all surrounding UI text."
    )
    confidence_score: float = Field(
        description="Confidence score from 0.0 to 1.0 that this is a valid target secret and not UI boilerplate."
    )


class DesktopEvent(BaseModel):
    application_name: str = Field(
        description="The normalized name of the application (e.g., 'Chrome', 'VSCode')."
    )
    window_title: str = Field(
        description="The specific context of the window (e.g., 'GitHub - Repository Settings')."
    )
    extracted_concepts: List[ScreenConcept] = Field(
        description="List of valid concepts found. If only UI boilerplate is present, this list MUST be empty."
    )


INGESTION_SYSTEM_PROMPT = """
You are a highly precise Data Extraction and Filtering Engine for a local Visual Firewall system named "Privex".
Your objective is to process noisy OCR output captured from a user's screen and extract only highly sensitive, targeted entities.

WARNING: The input text is generated by an optical character recognition (OCR) engine analyzing raw screen pixels. It will contain massive amounts of irrelevant UI boilerplate, operating system chrome, application menus, and rendering artifacts.

STRICT FILTERING RULES:
- You MUST IGNORE all application menu terms, including but not limited to: "File", "Edit", "View", "Insert", "Window", "Help", "Tools", "New Tab", "Settings", "Zoom", "Format".
- You MUST IGNORE fragmented, alphanumeric garbage that resembles OCR rendering artifacts (e.g., "Higw...", "keystxt").
- You may only extract entities that represent actual sensitive user data, specifically: API Keys, Passwords, Financial Data, or Credentials.
- If the input consists entirely of UI noise, document navigation, or if no valid target entities are present, you MUST return an empty list for extracted_concepts. Do not attempt to force noisy text into the schema.

REASONING PROTOCOL:
Before structuring the output, internally evaluate the text. Identify what parts represent the UI interface, what parts represent the document/window context, and what parts represent the actual target secret. Discard the UI and context entirely. Only map the isolated secret to the schema. Ensure the concept_value is completely stripped of surrounding descriptive text.
"""


def _parse_graph_json(raw_content: str) -> dict:
    content = (raw_content or "").strip()
    if not content:
        return {"applications": [], "secrets": [], "dates": []}

    try:
        payload = json.loads(content)
    except Exception:
        match = re.search(r"\{[\s\S]*\}", content)
        if not match:
            return {"applications": [], "secrets": [], "dates": []}
        try:
            payload = json.loads(match.group(0))
        except Exception:
            return {"applications": [], "secrets": [], "dates": []}

    applications = payload.get("applications") if isinstance(payload, dict) else []
    secrets = payload.get("secrets") if isinstance(payload, dict) else []
    dates = payload.get("dates") if isinstance(payload, dict) else []

    if not isinstance(applications, list):
        applications = []
    if not isinstance(secrets, list):
        secrets = []
    if not isinstance(dates, list):
        dates = []

    normalized_apps = [str(item).strip() for item in applications if str(item).strip()]
    normalized_dates = [str(item).strip() for item in dates if str(item).strip()]
    normalized_secrets = [str(item).strip() for item in secrets if str(item).strip()]

    return {
        "applications": normalized_apps,
        "secrets": normalized_secrets,
        "dates": normalized_dates,
    }


def _parse_desktop_event(raw_content: str, fallback_app: str) -> DesktopEvent | None:
    content = (raw_content or "").strip()
    if not content:
        return None

    try:
        payload = json.loads(content)
    except Exception:
        match = re.search(r"\{[\s\S]*\}", content)
        if not match:
            return None
        try:
            payload = json.loads(match.group(0))
        except Exception:
            return None

    if isinstance(payload, dict):
        payload.setdefault("application_name", fallback_app or "Unknown")
        payload.setdefault("window_title", "Unknown")
        payload.setdefault("extracted_concepts", [])

    try:
        return DesktopEvent.model_validate(payload)
    except ValidationError:
        return None

_last_saved_memory: dict[str, str] = {}


async def process_and_store_memory(ocr_text: str, active_app: str) -> None:
    try:
        ocr_text = (ocr_text or "").strip()
        active_app = (active_app or "").strip()

        if not ocr_text:
            return

        prompt = (
            f"You are an AI analyzing OCR text from a user's screen in the app: {active_app}. "
            "Summarize what the user is doing or looking at in ONE concise sentence. "
            "If the text is just an empty desktop or random UI noise, reply ONLY with the exact word 'NOISE'. "
            f"OCR Text: {ocr_text}"
        )

        response = await llm.ainvoke([HumanMessage(content=prompt)])
        new_summary = (getattr(response, "content", response) or "").strip()
        
        # 🛑 ADDED PRINT: See when it ignores useless screens
        if new_summary == "NOISE" or not new_summary:
            print(f"🙈 [Ingestion] Ignored noise in app: {active_app}")
            return

        # 🛑 ADDED PRINT: See the deduplication engine working
        if _last_saved_memory.get(active_app) == new_summary:
            print(f"♻️ [Ingestion] Deduplicated identical screen in: {active_app}")
            return

        _last_saved_memory[active_app] = new_summary

        vs = get_vector_store()
        if vs is None:
            print("[ingestion] vector store unavailable; skipping memory save.")
            return

        doc = Document(
            page_content=new_summary,
            metadata={
                "active_app": active_app,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            },
        )
        await asyncio.to_thread(vs.add_documents, [doc])

        # GraphRAG extraction path (additive to PGVector, never blocking the main pipeline)
        try:
            graph_store = get_graph_store()
            if graph_store is not None:
                graph_prompt = (
                    f"{INGESTION_SYSTEM_PROMPT}\n\n"
                    "Return ONLY valid JSON matching this schema:\n"
                    "{\n"
                    "  \"application_name\": \"string\",\n"
                    "  \"window_title\": \"string\",\n"
                    "  \"extracted_concepts\": [\n"
                    "    {\n"
                    "      \"concept_type\": \"API_KEY|PASSWORD|CREDENTIAL|FINANCIAL_DATA|PERSONAL_IDENTIFIER\",\n"
                    "      \"concept_value\": \"string\",\n"
                    "      \"confidence_score\": 0.0\n"
                    "    }\n"
                    "  ]\n"
                    "}\n\n"
                    f"App: {active_app}\n"
                    f"OCR Summary: {new_summary}"
                )
                graph_response = await llm.ainvoke([HumanMessage(content=graph_prompt)])
                graph_json_raw = getattr(graph_response, "content", graph_response)

                desktop_event = _parse_desktop_event(str(graph_json_raw), active_app)
                if desktop_event is not None:
                    applications = [desktop_event.application_name.strip()] if desktop_event.application_name.strip() else []
                    secrets = [
                        concept.concept_type.strip()
                        for concept in desktop_event.extracted_concepts
                        if concept.concept_type.strip()
                    ]
                    dates = [datetime.now(timezone.utc).date().isoformat()]
                else:
                    entities = _parse_graph_json(str(graph_json_raw))
                    applications = entities.get("applications", [])
                    secrets = entities.get("secrets", [])
                    dates = entities.get("dates", [])

                if active_app and active_app not in applications:
                    applications.append(active_app)
                if not dates:
                    dates.append(datetime.now(timezone.utc).date().isoformat())

                cypher = """
                MERGE (evt:Alert {id: $alert_id})
                SET evt.timestamp = $timestamp,
                    evt.risk_level = $risk_level,
                    evt.summary = $summary
                WITH evt
                UNWIND $applications AS app_name
                MERGE (a:Application {name: app_name})
                MERGE (evt)-[:OCCURRED_IN]->(a)
                WITH evt
                UNWIND $secrets AS secret_type
                MERGE (s:Secret {type: secret_type, redacted_preview: ''})
                MERGE (evt)-[:EXPOSED]->(s)
                WITH evt
                UNWIND $dates AS date_value
                MERGE (d:Date {date: date_value})
                MERGE (evt)-[:HAPPENED_ON]->(d)
                """

                params = {
                    "alert_id": f"mem-{uuid4()}",
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "risk_level": "High",
                    "summary": new_summary,
                    "applications": applications,
                    "secrets": secrets,
                    "dates": dates,
                }
                await asyncio.to_thread(graph_store.query, cypher, params)
        except Exception as graph_exc:
            print(f"[GraphRAG] Non-fatal graph ingestion error: {graph_exc}")
    except Exception as exc:
        print(f"[ingestion] memory ingestion error: {exc}")